---
os: linux
dist: jammy
language: python
python:
  - '3.10'
before_install:
  - pip install --upgrade pip setuptools
branches:
  only:
    - main
    - CD
jobs:
  include:
    - name: Check YAML format
      install:
        - pip install yamllint
      script:
        - yamllint .
    - name: test docker
      services:
        - docker
      script:
        - docker-compose up -d --build
        - curl localhost/
